create table COURSE(
	ID identity NOT NULL PRIMARY KEY,
	NAME VARCHAR(25) not null,
	CONSTRAINT UNIQUE_NAME UNIQUE (NAME)
);


CREATE TABLE T_PERSON (
  ID IDENTITY NOT NULL PRIMARY KEY,
  NAME  VARCHAR(50) NOT NULL,
  AGE INT,
  CONSTRAINT UNIQUE_NAME_1 UNIQUE (NAME)
);


create table STUDENT(
ID identity NOT NULL PRIMARY KEY,
LOGIN VARCHAR(20) not null,
NAME VARCHAR(15) not null,
EMAIL VARCHAR(25) not null,
CONSTRAINT UNIQUE_LOGIN UNIQUE (LOGIN));

create table REGISTRATION (
ID identity NOT NULL PRIMARY KEY,
STUDENTID INTEGER NOT NULL,
COURSEID INTEGER NOT NULL,
FOREIGN KEY (COURSEID) REFERENCES COURSE(ID),
FOREIGN KEY (STUDENTID) REFERENCES STUDENT(ID),
CONSTRAINT UNIQUE_REGISTRATION UNIQUE (STUDENTID,COURSEID)
);
